version: '3.8'

services:
  api:
    container_name: webrecipes-api
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - webrecipes-db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  webrecipes-db:
    image: postgres
    container_name: webrecipes-db
    environment:
      POSTGRES_USER: WebRecipes
      POSTGRES_PASSWORD: 10984
      POSTGRES_DB: webrecipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
